blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blog/', views.blog,name='blog'),
    path('<slug:slug>/',views.blogdetails, name='post-detail' ),
    path("category/<slug:slug>/posts", views.Posts_in_CategoryView, name="posts_in_category"),
   
    
]

home/urls.py
from django.urls import path, re_path

from . import views
from .views import SupplyDetails,MessageDetailView,MessageListView,message_create

urlpatterns = [
    path('', views.index, name='home'),
    path('test/', views.test, name='test'),
    path('message/', views.test, name='message'),
    path('message/list',MessageListView.as_view(), name='message-list'),
    path('message/detail/<pk>',MessageDetailView.as_view(), name='message-list'),
    path('message_create/<str:username>',message_create, name='message-create'),
    path('details/<slug:slug>/',views.exp_details, name='exp-details' ),
    path('favourite/<int:id>/',views.favourite,name='favourite'),
    path('favourites/', views.favourite_list, name='favourite_list'),
    path('supply/', views.supply, name='supply'),
    # path('reservation/', ReservationView.as_view(), name='reservation'),
    path('supply_details/<int:id>/<slug:slug>/',SupplyDetails.as_view(), name='supply-details' ),
    path('addcomment/<int:id>/',views.addcomment,name='addcomment'),
    path('filter-data',views.filter_data,name='filter_data'),
    # re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

tombitrip/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import search
from home import views as homeviews
# local
from user import views as userviews
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('blog/',include("blog.urls")),
    path('user/',include("user.urls")),
  
    path('contact/',include("contact.urls")),
    path('listvehicle/',include("listvehicle.urls")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    


    # local 
    path('search/',search,name='search'),
    path('supplysearch/',homeviews.supplysearch,name='supplysearch'),
    path('signup/',userviews.signup_form, name='signup_form'),
    path('login/',userviews.login_form, name='login_form'),
    path('logout/',userviews.logout_func, name='logout'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from ckeditor.fields import  RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime
from django.utils import timezone
from django.forms import ModelForm
from django.db.models import Avg, Count
import datetime
from django.forms import ModelForm
from django.conf import settings
from django.db.models.signals import post_save
from django.utils.html import mark_safe
# Create your models here.

class Experience(models.Model):
    title_keyword = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=False, unique=True)
    overview = RichTextUploadingField()
    image = models.ImageField(blank=True,null=True,upload_to='photos/%Y/%m/%d/')
    title1 = models.CharField(max_length=100)
    overview1 = RichTextUploadingField()
    image1 = models.ImageField(blank=True,null=True,upload_to='photos/%Y/%m/%d/')

    def __str__(self):
        return self.title_keyword

    def get_absolute_url(self):
        return reverse('exp-details', kwargs={
            'slug': self.slug
        })    
class Cartypes(models.Model):
    title = models.CharField(max_length=20)
    image=models.ImageField(blank=True,null=True, upload_to='photos/%Y/%m/%d/')

    def __str__(self):
        return self.title
class Category(models.Model):
    title = models.CharField(max_length=20)
    def __str__(self):
        return self.title
class Transmission(models.Model):
    title = models.CharField(max_length=30)
    def __str__(self):
        return self.title
class Supply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cartypes  = models.ManyToManyField(Cartypes)
    title = models.CharField(max_length=150)
    slug = models.SlugField(null=False, unique=True)
    car_title =  models.CharField(max_length=150)
    city =  models.CharField(max_length=150)
    price =  models.IntegerField()
    main_photo =  models.ImageField(upload_to='photos/%Y/%m/%d/') 
    image1 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image2 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image3 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image4 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image5 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image6 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image7 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image8 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image9 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image10 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image11 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image12 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image13 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image14 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image15 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image16 =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    image17=  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    seats =  models.IntegerField()
    bearth =  models.IntegerField()
    features = RichTextUploadingField()
    description = RichTextUploadingField()
    failities = RichTextUploadingField() 
    houserules = RichTextUploadingField()
    min_reserver_period = models.IntegerField()
    pick_up_from = models.TimeField(blank=True)
    drop_of_before = models.TimeField(blank=True)
    favourite = models.ManyToManyField(User,related_name='favourite',blank=True)
    is_published = models.BooleanField(default=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('/home')    
    def avaregereview(self):
        reviews = Rating.objects.filter(supply=self, status='True').aggregate(avarage=Avg('rate'))
        avg=0
        if reviews["avarage"] is not None:
            avg=float(reviews["avarage"])
        return avg

    def countreview(self):
        reviews = Rating.objects.filter(supply=self, status='True').aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt        
    # def get_absolute_url(self):
    #     return reverse('/home', kwargs={
    #         'slug': self.slug
    #     })   
    # def get_absolute_url(self):
    #     return reverse('supply-details',kwargs={'pk':self.pk})    
class ProductAttribute(models.Model):
    supply=models.ForeignKey(Supply,on_delete=models.CASCADE)
    price=models.PositiveIntegerField(default=0)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    transmission = models.ForeignKey(Transmission, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.supply.title
class Rating(models.Model):
    STATUS = (
        ('New', 'New'),
        ('True', 'True'),
        ('False', 'False'),
    )
    supply=models.ForeignKey(Supply,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, blank=True)
    comment = models.CharField(max_length=250,blank=True)
    rate = models.IntegerField(default=1)
    ip = models.CharField(max_length=20, blank=True)
    status=models.CharField(max_length=10,choices=STATUS, default='True')
    create_at=models.DateTimeField(default = timezone.now)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    supply=models.ForeignKey(Supply,on_delete=models.DO_NOTHING)
    start_date = models.DateField()
    end_date = models.DateField()
    location = models.CharField(max_length=50)
    confirm = models.BooleanField(null=True)

    def __str__(self):
        return self.location

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    supply = models.ForeignKey(Supply, on_delete=models.DO_NOTHING)
    time = models.DateField()
    message = models.CharField(max_length=150)

class CommentForm(ModelForm):
    class Meta:
        model = Rating
        fields = ['subject', 'comment', 'rate']


class Message(models.Model):
    toUser = models.ForeignKey(User, related_name='toUser', on_delete=models.DO_NOTHING, null=True)
    fromUser = models.ForeignKey(User, related_name='fromUser', on_delete=models.DO_NOTHING, null=True)
    message=models.TextField(null=True,blank=True,default='')
    update_at = models.DateTimeField(auto_now=True)
    location = models.CharField(max_length=150, null=True, blank=True, default='')

home/forms.py
from django import forms
from django.forms import ModelForm

from home.models import Supply, Reservation


class SupplyDetailsForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={"type": 'date', "id": 'from_date'})
    )
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={"type": 'date', "id": 'to_date'})
    )
    location = forms.CharField()

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ('confirm',)


class MessageForm(forms.Form):
    message = forms.CharField()

class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

home/templates/ajax/supply.html
<div class="col-lg-8 col-md-6 col-sm-12">
<div class="row" id="filteredProducts">
    <p class="ajaxLoader">Loading...</p>
    <!--item-->
    {% for supply in data %}
    
    <div class="col-md-6 col-sm-12 pt_30">
        <div class="vehicles-item">
            <div class="photo-list owl-carousel">
                <img src="{{supply.main_photo.url}}" alt="">
                
            </div>
            <div class="more-info">
                <a href=" {% url 'supply-details' supply.id supply.slug %} ">More info</a>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="text">
                        <div class="list">
                            <ul>
                                <li class="font-bold tt-product-head">{{supply.title}}<span class="right">
                                        <div class="review">
                                            <i class="fa fa-star{% if supply.avaregereview < 1%}-o empty{% endif%}"></i>
                                                <i class="fa fa-star{% if supply.avaregereview < 2%}-o empty{% endif%}"></i>
                                                <i class="fa fa-star{% if supply.avaregereview < 3%}-o empty{% endif%}"></i>
                                                <i class="fa fa-star{% if supply.avaregereview < 4%}-o empty{% endif%}"></i>
                                                <i class="fa fa-star{% if supply.avaregereview < 5%}-o empty{% endif%}"></i> {{ supply.avaregereview}}/{{ supply.countreview}}
                                        </div>
                                    </span>
                                </li>
                                <li class="li-middle">from €{{supply.productattribute_set.first.price}} per night <span class="right"></span></li>
                                <li>
                                    <div class="review r-bottom">
                                        <ul>
                                            <li><img src="https://d2g4biwrjrcyy4.cloudfront.net/img-resized/camptoo/icons/seats.svg" alt="">{{supply.seats}}</li>
                                            <li><i class="fa fa-bed" aria-hidden="true"></i> {{supply.bearth}}</li>
                                            <li><i class="fa fa-map-marker" aria-hidden="true"></i> {{supply.city}}</li>
                                        </ul>
                                    </div> 
                               
                                </li>
                            </ul>
                        </div>
                    </div>

                   
                </div>
            </div>
        </div>
    </div>
    {% empty %}
     <h1>No Supply list </h1>
    {% endfor %}

    <p class="my-4 text-center"><a href="products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
</div>
</div>